# Database Configuration
database:
  host: localhost
  port: 3000
  name: cable_data
  user: root
  password: root64
  
# Connection Settings
connection:
  pool:
    min: 0
    max: 10
  timeout: 10000

# Security Settings
security:
  ssl: true
  verify_cert: true